// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-support-bot/internal/app/datastruct"
	"go-support-bot/internal/app/service"

	"github.com/mymmrac/telego"
	"github.com/mymmrac/telego/telegohandler"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// ClearCacheBotClient provides a mock function for the type MockService
func (_mock *MockService) ClearCacheBotClient() {
	_mock.Called()
	return
}

// MockService_ClearCacheBotClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearCacheBotClient'
type MockService_ClearCacheBotClient_Call struct {
	*mock.Call
}

// ClearCacheBotClient is a helper method to define mock.On call
func (_e *MockService_Expecter) ClearCacheBotClient() *MockService_ClearCacheBotClient_Call {
	return &MockService_ClearCacheBotClient_Call{Call: _e.mock.On("ClearCacheBotClient")}
}

func (_c *MockService_ClearCacheBotClient_Call) Run(run func()) *MockService_ClearCacheBotClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_ClearCacheBotClient_Call) Return() *MockService_ClearCacheBotClient_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_ClearCacheBotClient_Call) RunAndReturn(run func()) *MockService_ClearCacheBotClient_Call {
	_c.Run(run)
	return _c
}

// ClearSession provides a mock function for the type MockService
func (_mock *MockService) ClearSession(ctx context.Context, customerID int64) error {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for ClearSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_ClearSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearSession'
type MockService_ClearSession_Call struct {
	*mock.Call
}

// ClearSession is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID int64
func (_e *MockService_Expecter) ClearSession(ctx interface{}, customerID interface{}) *MockService_ClearSession_Call {
	return &MockService_ClearSession_Call{Call: _e.mock.On("ClearSession", ctx, customerID)}
}

func (_c *MockService_ClearSession_Call) Run(run func(ctx context.Context, customerID int64)) *MockService_ClearSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ClearSession_Call) Return(err error) *MockService_ClearSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_ClearSession_Call) RunAndReturn(run func(ctx context.Context, customerID int64) error) *MockService_ClearSession_Call {
	_c.Call.Return(run)
	return _c
}

// CloseTopic provides a mock function for the type MockService
func (_mock *MockService) CloseTopic(ctx context.Context, topicID int) error {
	ret := _mock.Called(ctx, topicID)

	if len(ret) == 0 {
		panic("no return value specified for CloseTopic")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, topicID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_CloseTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseTopic'
type MockService_CloseTopic_Call struct {
	*mock.Call
}

// CloseTopic is a helper method to define mock.On call
//   - ctx context.Context
//   - topicID int
func (_e *MockService_Expecter) CloseTopic(ctx interface{}, topicID interface{}) *MockService_CloseTopic_Call {
	return &MockService_CloseTopic_Call{Call: _e.mock.On("CloseTopic", ctx, topicID)}
}

func (_c *MockService_CloseTopic_Call) Run(run func(ctx context.Context, topicID int)) *MockService_CloseTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CloseTopic_Call) Return(err error) *MockService_CloseTopic_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_CloseTopic_Call) RunAndReturn(run func(ctx context.Context, topicID int) error) *MockService_CloseTopic_Call {
	_c.Call.Return(run)
	return _c
}

// CloseTopicByClient provides a mock function for the type MockService
func (_mock *MockService) CloseTopicByClient(ctx context.Context, customerID int64) error {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for CloseTopicByClient")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_CloseTopicByClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseTopicByClient'
type MockService_CloseTopicByClient_Call struct {
	*mock.Call
}

// CloseTopicByClient is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID int64
func (_e *MockService_Expecter) CloseTopicByClient(ctx interface{}, customerID interface{}) *MockService_CloseTopicByClient_Call {
	return &MockService_CloseTopicByClient_Call{Call: _e.mock.On("CloseTopicByClient", ctx, customerID)}
}

func (_c *MockService_CloseTopicByClient_Call) Run(run func(ctx context.Context, customerID int64)) *MockService_CloseTopicByClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CloseTopicByClient_Call) Return(err error) *MockService_CloseTopicByClient_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_CloseTopicByClient_Call) RunAndReturn(run func(ctx context.Context, customerID int64) error) *MockService_CloseTopicByClient_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrReopenTopic provides a mock function for the type MockService
func (_mock *MockService) CreateOrReopenTopic(ctx context.Context, customerID int64, username string, fullName string, categoryID int, langCode string) error {
	ret := _mock.Called(ctx, customerID, username, fullName, categoryID, langCode)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrReopenTopic")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, int, string) error); ok {
		r0 = returnFunc(ctx, customerID, username, fullName, categoryID, langCode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_CreateOrReopenTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrReopenTopic'
type MockService_CreateOrReopenTopic_Call struct {
	*mock.Call
}

// CreateOrReopenTopic is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID int64
//   - username string
//   - fullName string
//   - categoryID int
//   - langCode string
func (_e *MockService_Expecter) CreateOrReopenTopic(ctx interface{}, customerID interface{}, username interface{}, fullName interface{}, categoryID interface{}, langCode interface{}) *MockService_CreateOrReopenTopic_Call {
	return &MockService_CreateOrReopenTopic_Call{Call: _e.mock.On("CreateOrReopenTopic", ctx, customerID, username, fullName, categoryID, langCode)}
}

func (_c *MockService_CreateOrReopenTopic_Call) Run(run func(ctx context.Context, customerID int64, username string, fullName string, categoryID int, langCode string)) *MockService_CreateOrReopenTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockService_CreateOrReopenTopic_Call) Return(err error) *MockService_CreateOrReopenTopic_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_CreateOrReopenTopic_Call) RunAndReturn(run func(ctx context.Context, customerID int64, username string, fullName string, categoryID int, langCode string) error) *MockService_CreateOrReopenTopic_Call {
	_c.Call.Return(run)
	return _c
}

// ExportCategoriesToYAML provides a mock function for the type MockService
func (_mock *MockService) ExportCategoriesToYAML(ctx context.Context) ([]byte, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ExportCategoriesToYAML")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ExportCategoriesToYAML_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportCategoriesToYAML'
type MockService_ExportCategoriesToYAML_Call struct {
	*mock.Call
}

// ExportCategoriesToYAML is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ExportCategoriesToYAML(ctx interface{}) *MockService_ExportCategoriesToYAML_Call {
	return &MockService_ExportCategoriesToYAML_Call{Call: _e.mock.On("ExportCategoriesToYAML", ctx)}
}

func (_c *MockService_ExportCategoriesToYAML_Call) Run(run func(ctx context.Context)) *MockService_ExportCategoriesToYAML_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ExportCategoriesToYAML_Call) Return(bytes []byte, err error) *MockService_ExportCategoriesToYAML_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockService_ExportCategoriesToYAML_Call) RunAndReturn(run func(ctx context.Context) ([]byte, error)) *MockService_ExportCategoriesToYAML_Call {
	_c.Call.Return(run)
	return _c
}

// ExportConfig provides a mock function for the type MockService
func (_mock *MockService) ExportConfig(ctx context.Context) (*service.YamlConfig, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ExportConfig")
	}

	var r0 *service.YamlConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*service.YamlConfig, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *service.YamlConfig); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.YamlConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ExportConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportConfig'
type MockService_ExportConfig_Call struct {
	*mock.Call
}

// ExportConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ExportConfig(ctx interface{}) *MockService_ExportConfig_Call {
	return &MockService_ExportConfig_Call{Call: _e.mock.On("ExportConfig", ctx)}
}

func (_c *MockService_ExportConfig_Call) Run(run func(ctx context.Context)) *MockService_ExportConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ExportConfig_Call) Return(yamlConfig *service.YamlConfig, err error) *MockService_ExportConfig_Call {
	_c.Call.Return(yamlConfig, err)
	return _c
}

func (_c *MockService_ExportConfig_Call) RunAndReturn(run func(ctx context.Context) (*service.YamlConfig, error)) *MockService_ExportConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetCategoriesKeyboard provides a mock function for the type MockService
func (_mock *MockService) GetCategoriesKeyboard(ctx context.Context, parentID *int) (*telego.InlineKeyboardMarkup, error) {
	ret := _mock.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoriesKeyboard")
	}

	var r0 *telego.InlineKeyboardMarkup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int) (*telego.InlineKeyboardMarkup, error)); ok {
		return returnFunc(ctx, parentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int) *telego.InlineKeyboardMarkup); ok {
		r0 = returnFunc(ctx, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telego.InlineKeyboardMarkup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *int) error); ok {
		r1 = returnFunc(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetCategoriesKeyboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategoriesKeyboard'
type MockService_GetCategoriesKeyboard_Call struct {
	*mock.Call
}

// GetCategoriesKeyboard is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID *int
func (_e *MockService_Expecter) GetCategoriesKeyboard(ctx interface{}, parentID interface{}) *MockService_GetCategoriesKeyboard_Call {
	return &MockService_GetCategoriesKeyboard_Call{Call: _e.mock.On("GetCategoriesKeyboard", ctx, parentID)}
}

func (_c *MockService_GetCategoriesKeyboard_Call) Run(run func(ctx context.Context, parentID *int)) *MockService_GetCategoriesKeyboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *int
		if args[1] != nil {
			arg1 = args[1].(*int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetCategoriesKeyboard_Call) Return(inlineKeyboardMarkup *telego.InlineKeyboardMarkup, err error) *MockService_GetCategoriesKeyboard_Call {
	_c.Call.Return(inlineKeyboardMarkup, err)
	return _c
}

func (_c *MockService_GetCategoriesKeyboard_Call) RunAndReturn(run func(ctx context.Context, parentID *int) (*telego.InlineKeyboardMarkup, error)) *MockService_GetCategoriesKeyboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetCategoryByID provides a mock function for the type MockService
func (_mock *MockService) GetCategoryByID(ctx context.Context, id int) (*datastruct.Category, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoryByID")
	}

	var r0 *datastruct.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*datastruct.Category, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *datastruct.Category); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*datastruct.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetCategoryByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategoryByID'
type MockService_GetCategoryByID_Call struct {
	*mock.Call
}

// GetCategoryByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockService_Expecter) GetCategoryByID(ctx interface{}, id interface{}) *MockService_GetCategoryByID_Call {
	return &MockService_GetCategoryByID_Call{Call: _e.mock.On("GetCategoryByID", ctx, id)}
}

func (_c *MockService_GetCategoryByID_Call) Run(run func(ctx context.Context, id int)) *MockService_GetCategoryByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetCategoryByID_Call) Return(category *datastruct.Category, err error) *MockService_GetCategoryByID_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *MockService_GetCategoryByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*datastruct.Category, error)) *MockService_GetCategoryByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomerID provides a mock function for the type MockService
func (_mock *MockService) GetCustomerID(ctx context.Context, topicID int) (int64, error) {
	ret := _mock.Called(ctx, topicID)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerID")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int64, error)); ok {
		return returnFunc(ctx, topicID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = returnFunc(ctx, topicID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, topicID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetCustomerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomerID'
type MockService_GetCustomerID_Call struct {
	*mock.Call
}

// GetCustomerID is a helper method to define mock.On call
//   - ctx context.Context
//   - topicID int
func (_e *MockService_Expecter) GetCustomerID(ctx interface{}, topicID interface{}) *MockService_GetCustomerID_Call {
	return &MockService_GetCustomerID_Call{Call: _e.mock.On("GetCustomerID", ctx, topicID)}
}

func (_c *MockService_GetCustomerID_Call) Run(run func(ctx context.Context, topicID int)) *MockService_GetCustomerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetCustomerID_Call) Return(n int64, err error) *MockService_GetCustomerID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockService_GetCustomerID_Call) RunAndReturn(run func(ctx context.Context, topicID int) (int64, error)) *MockService_GetCustomerID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomerTopic provides a mock function for the type MockService
func (_mock *MockService) GetCustomerTopic(ctx context.Context, id int64) (*datastruct.CustomerTopic, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerTopic")
	}

	var r0 *datastruct.CustomerTopic
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*datastruct.CustomerTopic, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *datastruct.CustomerTopic); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*datastruct.CustomerTopic)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetCustomerTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomerTopic'
type MockService_GetCustomerTopic_Call struct {
	*mock.Call
}

// GetCustomerTopic is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockService_Expecter) GetCustomerTopic(ctx interface{}, id interface{}) *MockService_GetCustomerTopic_Call {
	return &MockService_GetCustomerTopic_Call{Call: _e.mock.On("GetCustomerTopic", ctx, id)}
}

func (_c *MockService_GetCustomerTopic_Call) Run(run func(ctx context.Context, id int64)) *MockService_GetCustomerTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetCustomerTopic_Call) Return(customerTopic *datastruct.CustomerTopic, err error) *MockService_GetCustomerTopic_Call {
	_c.Call.Return(customerTopic, err)
	return _c
}

func (_c *MockService_GetCustomerTopic_Call) RunAndReturn(run func(ctx context.Context, id int64) (*datastruct.CustomerTopic, error)) *MockService_GetCustomerTopic_Call {
	_c.Call.Return(run)
	return _c
}

// GetMainPrompt provides a mock function for the type MockService
func (_mock *MockService) GetMainPrompt(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMainPrompt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetMainPrompt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMainPrompt'
type MockService_GetMainPrompt_Call struct {
	*mock.Call
}

// GetMainPrompt is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetMainPrompt(ctx interface{}) *MockService_GetMainPrompt_Call {
	return &MockService_GetMainPrompt_Call{Call: _e.mock.On("GetMainPrompt", ctx)}
}

func (_c *MockService_GetMainPrompt_Call) Run(run func(ctx context.Context)) *MockService_GetMainPrompt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetMainPrompt_Call) Return(s string, err error) *MockService_GetMainPrompt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_GetMainPrompt_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockService_GetMainPrompt_Call {
	_c.Call.Return(run)
	return _c
}

// GetManagersData provides a mock function for the type MockService
func (_mock *MockService) GetManagersData(ctx context.Context) ([]service.ManagerData, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetManagersData")
	}

	var r0 []service.ManagerData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]service.ManagerData, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []service.ManagerData); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.ManagerData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetManagersData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManagersData'
type MockService_GetManagersData_Call struct {
	*mock.Call
}

// GetManagersData is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetManagersData(ctx interface{}) *MockService_GetManagersData_Call {
	return &MockService_GetManagersData_Call{Call: _e.mock.On("GetManagersData", ctx)}
}

func (_c *MockService_GetManagersData_Call) Run(run func(ctx context.Context)) *MockService_GetManagersData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetManagersData_Call) Return(managerDatas []service.ManagerData, err error) *MockService_GetManagersData_Call {
	_c.Call.Return(managerDatas, err)
	return _c
}

func (_c *MockService_GetManagersData_Call) RunAndReturn(run func(ctx context.Context) ([]service.ManagerData, error)) *MockService_GetManagersData_Call {
	_c.Call.Return(run)
	return _c
}

// GetManagersList provides a mock function for the type MockService
func (_mock *MockService) GetManagersList(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetManagersList")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetManagersList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManagersList'
type MockService_GetManagersList_Call struct {
	*mock.Call
}

// GetManagersList is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetManagersList(ctx interface{}) *MockService_GetManagersList_Call {
	return &MockService_GetManagersList_Call{Call: _e.mock.On("GetManagersList", ctx)}
}

func (_c *MockService_GetManagersList_Call) Run(run func(ctx context.Context)) *MockService_GetManagersList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetManagersList_Call) Return(s string, err error) *MockService_GetManagersList_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_GetManagersList_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockService_GetManagersList_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessages provides a mock function for the type MockService
func (_mock *MockService) GetMessages(ctx context.Context) (service.YamlMessages, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 service.YamlMessages
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (service.YamlMessages, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) service.YamlMessages); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(service.YamlMessages)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessages'
type MockService_GetMessages_Call struct {
	*mock.Call
}

// GetMessages is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetMessages(ctx interface{}) *MockService_GetMessages_Call {
	return &MockService_GetMessages_Call{Call: _e.mock.On("GetMessages", ctx)}
}

func (_c *MockService_GetMessages_Call) Run(run func(ctx context.Context)) *MockService_GetMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetMessages_Call) Return(yamlMessages service.YamlMessages, err error) *MockService_GetMessages_Call {
	_c.Call.Return(yamlMessages, err)
	return _c
}

func (_c *MockService_GetMessages_Call) RunAndReturn(run func(ctx context.Context) (service.YamlMessages, error)) *MockService_GetMessages_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function for the type MockService
func (_mock *MockService) GetSession(ctx context.Context, customerID int64) (*datastruct.SessionData, error) {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *datastruct.SessionData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*datastruct.SessionData, error)); ok {
		return returnFunc(ctx, customerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *datastruct.SessionData); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*datastruct.SessionData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockService_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID int64
func (_e *MockService_Expecter) GetSession(ctx interface{}, customerID interface{}) *MockService_GetSession_Call {
	return &MockService_GetSession_Call{Call: _e.mock.On("GetSession", ctx, customerID)}
}

func (_c *MockService_GetSession_Call) Run(run func(ctx context.Context, customerID int64)) *MockService_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetSession_Call) Return(sessionData *datastruct.SessionData, err error) *MockService_GetSession_Call {
	_c.Call.Return(sessionData, err)
	return _c
}

func (_c *MockService_GetSession_Call) RunAndReturn(run func(ctx context.Context, customerID int64) (*datastruct.SessionData, error)) *MockService_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// HandleCustomerMessage provides a mock function for the type MockService
func (_mock *MockService) HandleCustomerMessage(ctx context.Context, msg *telego.Message) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for HandleCustomerMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *telego.Message) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_HandleCustomerMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleCustomerMessage'
type MockService_HandleCustomerMessage_Call struct {
	*mock.Call
}

// HandleCustomerMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *telego.Message
func (_e *MockService_Expecter) HandleCustomerMessage(ctx interface{}, msg interface{}) *MockService_HandleCustomerMessage_Call {
	return &MockService_HandleCustomerMessage_Call{Call: _e.mock.On("HandleCustomerMessage", ctx, msg)}
}

func (_c *MockService_HandleCustomerMessage_Call) Run(run func(ctx context.Context, msg *telego.Message)) *MockService_HandleCustomerMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *telego.Message
		if args[1] != nil {
			arg1 = args[1].(*telego.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_HandleCustomerMessage_Call) Return(err error) *MockService_HandleCustomerMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_HandleCustomerMessage_Call) RunAndReturn(run func(ctx context.Context, msg *telego.Message) error) *MockService_HandleCustomerMessage_Call {
	_c.Call.Return(run)
	return _c
}

// HandleManagerMessage provides a mock function for the type MockService
func (_mock *MockService) HandleManagerMessage(ctx context.Context, msg *telego.Message) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for HandleManagerMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *telego.Message) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_HandleManagerMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleManagerMessage'
type MockService_HandleManagerMessage_Call struct {
	*mock.Call
}

// HandleManagerMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *telego.Message
func (_e *MockService_Expecter) HandleManagerMessage(ctx interface{}, msg interface{}) *MockService_HandleManagerMessage_Call {
	return &MockService_HandleManagerMessage_Call{Call: _e.mock.On("HandleManagerMessage", ctx, msg)}
}

func (_c *MockService_HandleManagerMessage_Call) Run(run func(ctx context.Context, msg *telego.Message)) *MockService_HandleManagerMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *telego.Message
		if args[1] != nil {
			arg1 = args[1].(*telego.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_HandleManagerMessage_Call) Return(err error) *MockService_HandleManagerMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_HandleManagerMessage_Call) RunAndReturn(run func(ctx context.Context, msg *telego.Message) error) *MockService_HandleManagerMessage_Call {
	_c.Call.Return(run)
	return _c
}

// HasTopic provides a mock function for the type MockService
func (_mock *MockService) HasTopic(ctx context.Context, customerID int64) bool {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for HasTopic")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockService_HasTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasTopic'
type MockService_HasTopic_Call struct {
	*mock.Call
}

// HasTopic is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID int64
func (_e *MockService_Expecter) HasTopic(ctx interface{}, customerID interface{}) *MockService_HasTopic_Call {
	return &MockService_HasTopic_Call{Call: _e.mock.On("HasTopic", ctx, customerID)}
}

func (_c *MockService_HasTopic_Call) Run(run func(ctx context.Context, customerID int64)) *MockService_HasTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_HasTopic_Call) Return(b bool) *MockService_HasTopic_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockService_HasTopic_Call) RunAndReturn(run func(ctx context.Context, customerID int64) bool) *MockService_HasTopic_Call {
	_c.Call.Return(run)
	return _c
}

// ImportConfig provides a mock function for the type MockService
func (_mock *MockService) ImportConfig(ctx context.Context, cfg *service.YamlConfig) error {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for ImportConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *service.YamlConfig) error); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_ImportConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportConfig'
type MockService_ImportConfig_Call struct {
	*mock.Call
}

// ImportConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg *service.YamlConfig
func (_e *MockService_Expecter) ImportConfig(ctx interface{}, cfg interface{}) *MockService_ImportConfig_Call {
	return &MockService_ImportConfig_Call{Call: _e.mock.On("ImportConfig", ctx, cfg)}
}

func (_c *MockService_ImportConfig_Call) Run(run func(ctx context.Context, cfg *service.YamlConfig)) *MockService_ImportConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *service.YamlConfig
		if args[1] != nil {
			arg1 = args[1].(*service.YamlConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ImportConfig_Call) Return(err error) *MockService_ImportConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_ImportConfig_Call) RunAndReturn(run func(ctx context.Context, cfg *service.YamlConfig) error) *MockService_ImportConfig_Call {
	_c.Call.Return(run)
	return _c
}

// IsCustomer provides a mock function for the type MockService
func (_mock *MockService) IsCustomer() telegohandler.Predicate {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsCustomer")
	}

	var r0 telegohandler.Predicate
	if returnFunc, ok := ret.Get(0).(func() telegohandler.Predicate); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(telegohandler.Predicate)
		}
	}
	return r0
}

// MockService_IsCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsCustomer'
type MockService_IsCustomer_Call struct {
	*mock.Call
}

// IsCustomer is a helper method to define mock.On call
func (_e *MockService_Expecter) IsCustomer() *MockService_IsCustomer_Call {
	return &MockService_IsCustomer_Call{Call: _e.mock.On("IsCustomer")}
}

func (_c *MockService_IsCustomer_Call) Run(run func()) *MockService_IsCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_IsCustomer_Call) Return(predicate telegohandler.Predicate) *MockService_IsCustomer_Call {
	_c.Call.Return(predicate)
	return _c
}

func (_c *MockService_IsCustomer_Call) RunAndReturn(run func() telegohandler.Predicate) *MockService_IsCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// IsManager provides a mock function for the type MockService
func (_mock *MockService) IsManager(ctx context.Context, userID int64) bool {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsManager")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockService_IsManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsManager'
type MockService_IsManager_Call struct {
	*mock.Call
}

// IsManager is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockService_Expecter) IsManager(ctx interface{}, userID interface{}) *MockService_IsManager_Call {
	return &MockService_IsManager_Call{Call: _e.mock.On("IsManager", ctx, userID)}
}

func (_c *MockService_IsManager_Call) Run(run func(ctx context.Context, userID int64)) *MockService_IsManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_IsManager_Call) Return(b bool) *MockService_IsManager_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockService_IsManager_Call) RunAndReturn(run func(ctx context.Context, userID int64) bool) *MockService_IsManager_Call {
	_c.Call.Return(run)
	return _c
}

// LoadCategoriesFromYAML provides a mock function for the type MockService
func (_mock *MockService) LoadCategoriesFromYAML(ctx context.Context, data []byte) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for LoadCategoriesFromYAML")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_LoadCategoriesFromYAML_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadCategoriesFromYAML'
type MockService_LoadCategoriesFromYAML_Call struct {
	*mock.Call
}

// LoadCategoriesFromYAML is a helper method to define mock.On call
//   - ctx context.Context
//   - data []byte
func (_e *MockService_Expecter) LoadCategoriesFromYAML(ctx interface{}, data interface{}) *MockService_LoadCategoriesFromYAML_Call {
	return &MockService_LoadCategoriesFromYAML_Call{Call: _e.mock.On("LoadCategoriesFromYAML", ctx, data)}
}

func (_c *MockService_LoadCategoriesFromYAML_Call) Run(run func(ctx context.Context, data []byte)) *MockService_LoadCategoriesFromYAML_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_LoadCategoriesFromYAML_Call) Return(err error) *MockService_LoadCategoriesFromYAML_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_LoadCategoriesFromYAML_Call) RunAndReturn(run func(ctx context.Context, data []byte) error) *MockService_LoadCategoriesFromYAML_Call {
	_c.Call.Return(run)
	return _c
}

// SaveName provides a mock function for the type MockService
func (_mock *MockService) SaveName(ctx context.Context, customerID int64, name string) error {
	ret := _mock.Called(ctx, customerID, name)

	if len(ret) == 0 {
		panic("no return value specified for SaveName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, customerID, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SaveName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveName'
type MockService_SaveName_Call struct {
	*mock.Call
}

// SaveName is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID int64
//   - name string
func (_e *MockService_Expecter) SaveName(ctx interface{}, customerID interface{}, name interface{}) *MockService_SaveName_Call {
	return &MockService_SaveName_Call{Call: _e.mock.On("SaveName", ctx, customerID, name)}
}

func (_c *MockService_SaveName_Call) Run(run func(ctx context.Context, customerID int64, name string)) *MockService_SaveName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_SaveName_Call) Return(err error) *MockService_SaveName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SaveName_Call) RunAndReturn(run func(ctx context.Context, customerID int64, name string) error) *MockService_SaveName_Call {
	_c.Call.Return(run)
	return _c
}

// SetCustomerLangByTopic provides a mock function for the type MockService
func (_mock *MockService) SetCustomerLangByTopic(ctx context.Context, topicID int, langCode string) error {
	ret := _mock.Called(ctx, topicID, langCode)

	if len(ret) == 0 {
		panic("no return value specified for SetCustomerLangByTopic")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = returnFunc(ctx, topicID, langCode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SetCustomerLangByTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCustomerLangByTopic'
type MockService_SetCustomerLangByTopic_Call struct {
	*mock.Call
}

// SetCustomerLangByTopic is a helper method to define mock.On call
//   - ctx context.Context
//   - topicID int
//   - langCode string
func (_e *MockService_Expecter) SetCustomerLangByTopic(ctx interface{}, topicID interface{}, langCode interface{}) *MockService_SetCustomerLangByTopic_Call {
	return &MockService_SetCustomerLangByTopic_Call{Call: _e.mock.On("SetCustomerLangByTopic", ctx, topicID, langCode)}
}

func (_c *MockService_SetCustomerLangByTopic_Call) Run(run func(ctx context.Context, topicID int, langCode string)) *MockService_SetCustomerLangByTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_SetCustomerLangByTopic_Call) Return(err error) *MockService_SetCustomerLangByTopic_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SetCustomerLangByTopic_Call) RunAndReturn(run func(ctx context.Context, topicID int, langCode string) error) *MockService_SetCustomerLangByTopic_Call {
	_c.Call.Return(run)
	return _c
}

// SetWaitingName provides a mock function for the type MockService
func (_mock *MockService) SetWaitingName(ctx context.Context, customerID int64) error {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for SetWaitingName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SetWaitingName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWaitingName'
type MockService_SetWaitingName_Call struct {
	*mock.Call
}

// SetWaitingName is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID int64
func (_e *MockService_Expecter) SetWaitingName(ctx interface{}, customerID interface{}) *MockService_SetWaitingName_Call {
	return &MockService_SetWaitingName_Call{Call: _e.mock.On("SetWaitingName", ctx, customerID)}
}

func (_c *MockService_SetWaitingName_Call) Run(run func(ctx context.Context, customerID int64)) *MockService_SetWaitingName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_SetWaitingName_Call) Return(err error) *MockService_SetWaitingName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SetWaitingName_Call) RunAndReturn(run func(ctx context.Context, customerID int64) error) *MockService_SetWaitingName_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleTestMode provides a mock function for the type MockService
func (_mock *MockService) ToggleTestMode(userID int64) bool {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for ToggleTestMode")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(int64) bool); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockService_ToggleTestMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleTestMode'
type MockService_ToggleTestMode_Call struct {
	*mock.Call
}

// ToggleTestMode is a helper method to define mock.On call
//   - userID int64
func (_e *MockService_Expecter) ToggleTestMode(userID interface{}) *MockService_ToggleTestMode_Call {
	return &MockService_ToggleTestMode_Call{Call: _e.mock.On("ToggleTestMode", userID)}
}

func (_c *MockService_ToggleTestMode_Call) Run(run func(userID int64)) *MockService_ToggleTestMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ToggleTestMode_Call) Return(b bool) *MockService_ToggleTestMode_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockService_ToggleTestMode_Call) RunAndReturn(run func(userID int64) bool) *MockService_ToggleTestMode_Call {
	_c.Call.Return(run)
	return _c
}
