// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-support-bot/internal/app/datastruct"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CheckAndCompleteBroadcast provides a mock function for the type MockRepository
func (_mock *MockRepository) CheckAndCompleteBroadcast(ctx context.Context, broadcastID int) error {
	ret := _mock.Called(ctx, broadcastID)

	if len(ret) == 0 {
		panic("no return value specified for CheckAndCompleteBroadcast")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, broadcastID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CheckAndCompleteBroadcast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckAndCompleteBroadcast'
type MockRepository_CheckAndCompleteBroadcast_Call struct {
	*mock.Call
}

// CheckAndCompleteBroadcast is a helper method to define mock.On call
//   - ctx context.Context
//   - broadcastID int
func (_e *MockRepository_Expecter) CheckAndCompleteBroadcast(ctx interface{}, broadcastID interface{}) *MockRepository_CheckAndCompleteBroadcast_Call {
	return &MockRepository_CheckAndCompleteBroadcast_Call{Call: _e.mock.On("CheckAndCompleteBroadcast", ctx, broadcastID)}
}

func (_c *MockRepository_CheckAndCompleteBroadcast_Call) Run(run func(ctx context.Context, broadcastID int)) *MockRepository_CheckAndCompleteBroadcast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CheckAndCompleteBroadcast_Call) Return(err error) *MockRepository_CheckAndCompleteBroadcast_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CheckAndCompleteBroadcast_Call) RunAndReturn(run func(ctx context.Context, broadcastID int) error) *MockRepository_CheckAndCompleteBroadcast_Call {
	_c.Call.Return(run)
	return _c
}

// ClearSession provides a mock function for the type MockRepository
func (_mock *MockRepository) ClearSession(ctx context.Context, customerID int64) error {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for ClearSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_ClearSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearSession'
type MockRepository_ClearSession_Call struct {
	*mock.Call
}

// ClearSession is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID int64
func (_e *MockRepository_Expecter) ClearSession(ctx interface{}, customerID interface{}) *MockRepository_ClearSession_Call {
	return &MockRepository_ClearSession_Call{Call: _e.mock.On("ClearSession", ctx, customerID)}
}

func (_c *MockRepository_ClearSession_Call) Run(run func(ctx context.Context, customerID int64)) *MockRepository_ClearSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ClearSession_Call) Return(err error) *MockRepository_ClearSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_ClearSession_Call) RunAndReturn(run func(ctx context.Context, customerID int64) error) *MockRepository_ClearSession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBroadcast provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateBroadcast(ctx context.Context, text string, customerIDs []int64) (int, error) {
	ret := _mock.Called(ctx, text, customerIDs)

	if len(ret) == 0 {
		panic("no return value specified for CreateBroadcast")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []int64) (int, error)); ok {
		return returnFunc(ctx, text, customerIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []int64) int); ok {
		r0 = returnFunc(ctx, text, customerIDs)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []int64) error); ok {
		r1 = returnFunc(ctx, text, customerIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateBroadcast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBroadcast'
type MockRepository_CreateBroadcast_Call struct {
	*mock.Call
}

// CreateBroadcast is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
//   - customerIDs []int64
func (_e *MockRepository_Expecter) CreateBroadcast(ctx interface{}, text interface{}, customerIDs interface{}) *MockRepository_CreateBroadcast_Call {
	return &MockRepository_CreateBroadcast_Call{Call: _e.mock.On("CreateBroadcast", ctx, text, customerIDs)}
}

func (_c *MockRepository_CreateBroadcast_Call) Run(run func(ctx context.Context, text string, customerIDs []int64)) *MockRepository_CreateBroadcast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []int64
		if args[2] != nil {
			arg2 = args[2].([]int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_CreateBroadcast_Call) Return(n int, err error) *MockRepository_CreateBroadcast_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_CreateBroadcast_Call) RunAndReturn(run func(ctx context.Context, text string, customerIDs []int64) (int, error)) *MockRepository_CreateBroadcast_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllCategoriesFull provides a mock function for the type MockRepository
func (_mock *MockRepository) GetAllCategoriesFull(ctx context.Context) ([]datastruct.Category, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCategoriesFull")
	}

	var r0 []datastruct.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]datastruct.Category, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []datastruct.Category); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datastruct.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetAllCategoriesFull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllCategoriesFull'
type MockRepository_GetAllCategoriesFull_Call struct {
	*mock.Call
}

// GetAllCategoriesFull is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetAllCategoriesFull(ctx interface{}) *MockRepository_GetAllCategoriesFull_Call {
	return &MockRepository_GetAllCategoriesFull_Call{Call: _e.mock.On("GetAllCategoriesFull", ctx)}
}

func (_c *MockRepository_GetAllCategoriesFull_Call) Run(run func(ctx context.Context)) *MockRepository_GetAllCategoriesFull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetAllCategoriesFull_Call) Return(categorys []datastruct.Category, err error) *MockRepository_GetAllCategoriesFull_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *MockRepository_GetAllCategoriesFull_Call) RunAndReturn(run func(ctx context.Context) ([]datastruct.Category, error)) *MockRepository_GetAllCategoriesFull_Call {
	_c.Call.Return(run)
	return _c
}

// GetBroadcasts provides a mock function for the type MockRepository
func (_mock *MockRepository) GetBroadcasts(ctx context.Context) ([]datastruct.Broadcast, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetBroadcasts")
	}

	var r0 []datastruct.Broadcast
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]datastruct.Broadcast, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []datastruct.Broadcast); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datastruct.Broadcast)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetBroadcasts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBroadcasts'
type MockRepository_GetBroadcasts_Call struct {
	*mock.Call
}

// GetBroadcasts is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetBroadcasts(ctx interface{}) *MockRepository_GetBroadcasts_Call {
	return &MockRepository_GetBroadcasts_Call{Call: _e.mock.On("GetBroadcasts", ctx)}
}

func (_c *MockRepository_GetBroadcasts_Call) Run(run func(ctx context.Context)) *MockRepository_GetBroadcasts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetBroadcasts_Call) Return(broadcasts []datastruct.Broadcast, err error) *MockRepository_GetBroadcasts_Call {
	_c.Call.Return(broadcasts, err)
	return _c
}

func (_c *MockRepository_GetBroadcasts_Call) RunAndReturn(run func(ctx context.Context) ([]datastruct.Broadcast, error)) *MockRepository_GetBroadcasts_Call {
	_c.Call.Return(run)
	return _c
}

// GetCategoriesByParent provides a mock function for the type MockRepository
func (_mock *MockRepository) GetCategoriesByParent(ctx context.Context, parentID *int) ([]datastruct.Category, error) {
	ret := _mock.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoriesByParent")
	}

	var r0 []datastruct.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int) ([]datastruct.Category, error)); ok {
		return returnFunc(ctx, parentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int) []datastruct.Category); ok {
		r0 = returnFunc(ctx, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datastruct.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *int) error); ok {
		r1 = returnFunc(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetCategoriesByParent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategoriesByParent'
type MockRepository_GetCategoriesByParent_Call struct {
	*mock.Call
}

// GetCategoriesByParent is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID *int
func (_e *MockRepository_Expecter) GetCategoriesByParent(ctx interface{}, parentID interface{}) *MockRepository_GetCategoriesByParent_Call {
	return &MockRepository_GetCategoriesByParent_Call{Call: _e.mock.On("GetCategoriesByParent", ctx, parentID)}
}

func (_c *MockRepository_GetCategoriesByParent_Call) Run(run func(ctx context.Context, parentID *int)) *MockRepository_GetCategoriesByParent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *int
		if args[1] != nil {
			arg1 = args[1].(*int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetCategoriesByParent_Call) Return(categorys []datastruct.Category, err error) *MockRepository_GetCategoriesByParent_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *MockRepository_GetCategoriesByParent_Call) RunAndReturn(run func(ctx context.Context, parentID *int) ([]datastruct.Category, error)) *MockRepository_GetCategoriesByParent_Call {
	_c.Call.Return(run)
	return _c
}

// GetCategoryByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetCategoryByID(ctx context.Context, id int) (*datastruct.Category, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoryByID")
	}

	var r0 *datastruct.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*datastruct.Category, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *datastruct.Category); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*datastruct.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetCategoryByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategoryByID'
type MockRepository_GetCategoryByID_Call struct {
	*mock.Call
}

// GetCategoryByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockRepository_Expecter) GetCategoryByID(ctx interface{}, id interface{}) *MockRepository_GetCategoryByID_Call {
	return &MockRepository_GetCategoryByID_Call{Call: _e.mock.On("GetCategoryByID", ctx, id)}
}

func (_c *MockRepository_GetCategoryByID_Call) Run(run func(ctx context.Context, id int)) *MockRepository_GetCategoryByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetCategoryByID_Call) Return(category *datastruct.Category, err error) *MockRepository_GetCategoryByID_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *MockRepository_GetCategoryByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*datastruct.Category, error)) *MockRepository_GetCategoryByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomerID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetCustomerID(ctx context.Context, topicID int) (int64, error) {
	ret := _mock.Called(ctx, topicID)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerID")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (int64, error)); ok {
		return returnFunc(ctx, topicID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) int64); ok {
		r0 = returnFunc(ctx, topicID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, topicID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetCustomerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomerID'
type MockRepository_GetCustomerID_Call struct {
	*mock.Call
}

// GetCustomerID is a helper method to define mock.On call
//   - ctx context.Context
//   - topicID int
func (_e *MockRepository_Expecter) GetCustomerID(ctx interface{}, topicID interface{}) *MockRepository_GetCustomerID_Call {
	return &MockRepository_GetCustomerID_Call{Call: _e.mock.On("GetCustomerID", ctx, topicID)}
}

func (_c *MockRepository_GetCustomerID_Call) Run(run func(ctx context.Context, topicID int)) *MockRepository_GetCustomerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetCustomerID_Call) Return(n int64, err error) *MockRepository_GetCustomerID_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_GetCustomerID_Call) RunAndReturn(run func(ctx context.Context, topicID int) (int64, error)) *MockRepository_GetCustomerID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomerProfiles provides a mock function for the type MockRepository
func (_mock *MockRepository) GetCustomerProfiles(ctx context.Context, search string) ([]datastruct.CustomerProfile, error) {
	ret := _mock.Called(ctx, search)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerProfiles")
	}

	var r0 []datastruct.CustomerProfile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]datastruct.CustomerProfile, error)); ok {
		return returnFunc(ctx, search)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []datastruct.CustomerProfile); ok {
		r0 = returnFunc(ctx, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datastruct.CustomerProfile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, search)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetCustomerProfiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomerProfiles'
type MockRepository_GetCustomerProfiles_Call struct {
	*mock.Call
}

// GetCustomerProfiles is a helper method to define mock.On call
//   - ctx context.Context
//   - search string
func (_e *MockRepository_Expecter) GetCustomerProfiles(ctx interface{}, search interface{}) *MockRepository_GetCustomerProfiles_Call {
	return &MockRepository_GetCustomerProfiles_Call{Call: _e.mock.On("GetCustomerProfiles", ctx, search)}
}

func (_c *MockRepository_GetCustomerProfiles_Call) Run(run func(ctx context.Context, search string)) *MockRepository_GetCustomerProfiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetCustomerProfiles_Call) Return(customerProfiles []datastruct.CustomerProfile, err error) *MockRepository_GetCustomerProfiles_Call {
	_c.Call.Return(customerProfiles, err)
	return _c
}

func (_c *MockRepository_GetCustomerProfiles_Call) RunAndReturn(run func(ctx context.Context, search string) ([]datastruct.CustomerProfile, error)) *MockRepository_GetCustomerProfiles_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomerTopic provides a mock function for the type MockRepository
func (_mock *MockRepository) GetCustomerTopic(ctx context.Context, customerID int64) (*datastruct.CustomerTopic, error) {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerTopic")
	}

	var r0 *datastruct.CustomerTopic
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*datastruct.CustomerTopic, error)); ok {
		return returnFunc(ctx, customerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *datastruct.CustomerTopic); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*datastruct.CustomerTopic)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetCustomerTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomerTopic'
type MockRepository_GetCustomerTopic_Call struct {
	*mock.Call
}

// GetCustomerTopic is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID int64
func (_e *MockRepository_Expecter) GetCustomerTopic(ctx interface{}, customerID interface{}) *MockRepository_GetCustomerTopic_Call {
	return &MockRepository_GetCustomerTopic_Call{Call: _e.mock.On("GetCustomerTopic", ctx, customerID)}
}

func (_c *MockRepository_GetCustomerTopic_Call) Run(run func(ctx context.Context, customerID int64)) *MockRepository_GetCustomerTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetCustomerTopic_Call) Return(customerTopic *datastruct.CustomerTopic, err error) *MockRepository_GetCustomerTopic_Call {
	_c.Call.Return(customerTopic, err)
	return _c
}

func (_c *MockRepository_GetCustomerTopic_Call) RunAndReturn(run func(ctx context.Context, customerID int64) (*datastruct.CustomerTopic, error)) *MockRepository_GetCustomerTopic_Call {
	_c.Call.Return(run)
	return _c
}

// GetMainPrompt provides a mock function for the type MockRepository
func (_mock *MockRepository) GetMainPrompt(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMainPrompt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetMainPrompt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMainPrompt'
type MockRepository_GetMainPrompt_Call struct {
	*mock.Call
}

// GetMainPrompt is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetMainPrompt(ctx interface{}) *MockRepository_GetMainPrompt_Call {
	return &MockRepository_GetMainPrompt_Call{Call: _e.mock.On("GetMainPrompt", ctx)}
}

func (_c *MockRepository_GetMainPrompt_Call) Run(run func(ctx context.Context)) *MockRepository_GetMainPrompt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetMainPrompt_Call) Return(s string, err error) *MockRepository_GetMainPrompt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRepository_GetMainPrompt_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockRepository_GetMainPrompt_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingBroadcastTasks provides a mock function for the type MockRepository
func (_mock *MockRepository) GetPendingBroadcastTasks(ctx context.Context, limit int) ([]datastruct.BroadcastTask, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingBroadcastTasks")
	}

	var r0 []datastruct.BroadcastTask
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]datastruct.BroadcastTask, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []datastruct.BroadcastTask); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datastruct.BroadcastTask)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetPendingBroadcastTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingBroadcastTasks'
type MockRepository_GetPendingBroadcastTasks_Call struct {
	*mock.Call
}

// GetPendingBroadcastTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockRepository_Expecter) GetPendingBroadcastTasks(ctx interface{}, limit interface{}) *MockRepository_GetPendingBroadcastTasks_Call {
	return &MockRepository_GetPendingBroadcastTasks_Call{Call: _e.mock.On("GetPendingBroadcastTasks", ctx, limit)}
}

func (_c *MockRepository_GetPendingBroadcastTasks_Call) Run(run func(ctx context.Context, limit int)) *MockRepository_GetPendingBroadcastTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetPendingBroadcastTasks_Call) Return(broadcastTasks []datastruct.BroadcastTask, err error) *MockRepository_GetPendingBroadcastTasks_Call {
	_c.Call.Return(broadcastTasks, err)
	return _c
}

func (_c *MockRepository_GetPendingBroadcastTasks_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]datastruct.BroadcastTask, error)) *MockRepository_GetPendingBroadcastTasks_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function for the type MockRepository
func (_mock *MockRepository) GetSession(ctx context.Context, customerID int64) (*datastruct.SessionData, error) {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *datastruct.SessionData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*datastruct.SessionData, error)); ok {
		return returnFunc(ctx, customerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *datastruct.SessionData); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*datastruct.SessionData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockRepository_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID int64
func (_e *MockRepository_Expecter) GetSession(ctx interface{}, customerID interface{}) *MockRepository_GetSession_Call {
	return &MockRepository_GetSession_Call{Call: _e.mock.On("GetSession", ctx, customerID)}
}

func (_c *MockRepository_GetSession_Call) Run(run func(ctx context.Context, customerID int64)) *MockRepository_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetSession_Call) Return(sessionData *datastruct.SessionData, err error) *MockRepository_GetSession_Call {
	_c.Call.Return(sessionData, err)
	return _c
}

func (_c *MockRepository_GetSession_Call) RunAndReturn(run func(ctx context.Context, customerID int64) (*datastruct.SessionData, error)) *MockRepository_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSetting provides a mock function for the type MockRepository
func (_mock *MockRepository) GetSetting(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetSetting")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSetting'
type MockRepository_GetSetting_Call struct {
	*mock.Call
}

// GetSetting is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockRepository_Expecter) GetSetting(ctx interface{}, key interface{}) *MockRepository_GetSetting_Call {
	return &MockRepository_GetSetting_Call{Call: _e.mock.On("GetSetting", ctx, key)}
}

func (_c *MockRepository_GetSetting_Call) Run(run func(ctx context.Context, key string)) *MockRepository_GetSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetSetting_Call) Return(s string, err error) *MockRepository_GetSetting_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRepository_GetSetting_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockRepository_GetSetting_Call {
	_c.Call.Return(run)
	return _c
}

// MarkCustomerAsBlocked provides a mock function for the type MockRepository
func (_mock *MockRepository) MarkCustomerAsBlocked(ctx context.Context, customerID int64) error {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for MarkCustomerAsBlocked")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_MarkCustomerAsBlocked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkCustomerAsBlocked'
type MockRepository_MarkCustomerAsBlocked_Call struct {
	*mock.Call
}

// MarkCustomerAsBlocked is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID int64
func (_e *MockRepository_Expecter) MarkCustomerAsBlocked(ctx interface{}, customerID interface{}) *MockRepository_MarkCustomerAsBlocked_Call {
	return &MockRepository_MarkCustomerAsBlocked_Call{Call: _e.mock.On("MarkCustomerAsBlocked", ctx, customerID)}
}

func (_c *MockRepository_MarkCustomerAsBlocked_Call) Run(run func(ctx context.Context, customerID int64)) *MockRepository_MarkCustomerAsBlocked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_MarkCustomerAsBlocked_Call) Return(err error) *MockRepository_MarkCustomerAsBlocked_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_MarkCustomerAsBlocked_Call) RunAndReturn(run func(ctx context.Context, customerID int64) error) *MockRepository_MarkCustomerAsBlocked_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceCategoriesTree provides a mock function for the type MockRepository
func (_mock *MockRepository) ReplaceCategoriesTree(ctx context.Context, mainPrompt string, messagesJSON []byte, roots []*datastruct.CategoryNode) error {
	ret := _mock.Called(ctx, mainPrompt, messagesJSON, roots)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceCategoriesTree")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, []*datastruct.CategoryNode) error); ok {
		r0 = returnFunc(ctx, mainPrompt, messagesJSON, roots)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_ReplaceCategoriesTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceCategoriesTree'
type MockRepository_ReplaceCategoriesTree_Call struct {
	*mock.Call
}

// ReplaceCategoriesTree is a helper method to define mock.On call
//   - ctx context.Context
//   - mainPrompt string
//   - messagesJSON []byte
//   - roots []*datastruct.CategoryNode
func (_e *MockRepository_Expecter) ReplaceCategoriesTree(ctx interface{}, mainPrompt interface{}, messagesJSON interface{}, roots interface{}) *MockRepository_ReplaceCategoriesTree_Call {
	return &MockRepository_ReplaceCategoriesTree_Call{Call: _e.mock.On("ReplaceCategoriesTree", ctx, mainPrompt, messagesJSON, roots)}
}

func (_c *MockRepository_ReplaceCategoriesTree_Call) Run(run func(ctx context.Context, mainPrompt string, messagesJSON []byte, roots []*datastruct.CategoryNode)) *MockRepository_ReplaceCategoriesTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 []*datastruct.CategoryNode
		if args[3] != nil {
			arg3 = args[3].([]*datastruct.CategoryNode)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_ReplaceCategoriesTree_Call) Return(err error) *MockRepository_ReplaceCategoriesTree_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_ReplaceCategoriesTree_Call) RunAndReturn(run func(ctx context.Context, mainPrompt string, messagesJSON []byte, roots []*datastruct.CategoryNode) error) *MockRepository_ReplaceCategoriesTree_Call {
	_c.Call.Return(run)
	return _c
}

// RetryBroadcast provides a mock function for the type MockRepository
func (_mock *MockRepository) RetryBroadcast(ctx context.Context, broadcastID int) error {
	ret := _mock.Called(ctx, broadcastID)

	if len(ret) == 0 {
		panic("no return value specified for RetryBroadcast")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, broadcastID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_RetryBroadcast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryBroadcast'
type MockRepository_RetryBroadcast_Call struct {
	*mock.Call
}

// RetryBroadcast is a helper method to define mock.On call
//   - ctx context.Context
//   - broadcastID int
func (_e *MockRepository_Expecter) RetryBroadcast(ctx interface{}, broadcastID interface{}) *MockRepository_RetryBroadcast_Call {
	return &MockRepository_RetryBroadcast_Call{Call: _e.mock.On("RetryBroadcast", ctx, broadcastID)}
}

func (_c *MockRepository_RetryBroadcast_Call) Run(run func(ctx context.Context, broadcastID int)) *MockRepository_RetryBroadcast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_RetryBroadcast_Call) Return(err error) *MockRepository_RetryBroadcast_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_RetryBroadcast_Call) RunAndReturn(run func(ctx context.Context, broadcastID int) error) *MockRepository_RetryBroadcast_Call {
	_c.Call.Return(run)
	return _c
}

// SaveCustomer provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveCustomer(ctx context.Context, id int64, fullName string, username string) error {
	ret := _mock.Called(ctx, id, fullName, username)

	if len(ret) == 0 {
		panic("no return value specified for SaveCustomer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string) error); ok {
		r0 = returnFunc(ctx, id, fullName, username)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SaveCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveCustomer'
type MockRepository_SaveCustomer_Call struct {
	*mock.Call
}

// SaveCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - fullName string
//   - username string
func (_e *MockRepository_Expecter) SaveCustomer(ctx interface{}, id interface{}, fullName interface{}, username interface{}) *MockRepository_SaveCustomer_Call {
	return &MockRepository_SaveCustomer_Call{Call: _e.mock.On("SaveCustomer", ctx, id, fullName, username)}
}

func (_c *MockRepository_SaveCustomer_Call) Run(run func(ctx context.Context, id int64, fullName string, username string)) *MockRepository_SaveCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_SaveCustomer_Call) Return(err error) *MockRepository_SaveCustomer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SaveCustomer_Call) RunAndReturn(run func(ctx context.Context, id int64, fullName string, username string) error) *MockRepository_SaveCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// SaveName provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveName(ctx context.Context, customerID int64, name string) error {
	ret := _mock.Called(ctx, customerID, name)

	if len(ret) == 0 {
		panic("no return value specified for SaveName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, customerID, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SaveName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveName'
type MockRepository_SaveName_Call struct {
	*mock.Call
}

// SaveName is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID int64
//   - name string
func (_e *MockRepository_Expecter) SaveName(ctx interface{}, customerID interface{}, name interface{}) *MockRepository_SaveName_Call {
	return &MockRepository_SaveName_Call{Call: _e.mock.On("SaveName", ctx, customerID, name)}
}

func (_c *MockRepository_SaveName_Call) Run(run func(ctx context.Context, customerID int64, name string)) *MockRepository_SaveName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_SaveName_Call) Return(err error) *MockRepository_SaveName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SaveName_Call) RunAndReturn(run func(ctx context.Context, customerID int64, name string) error) *MockRepository_SaveName_Call {
	_c.Call.Return(run)
	return _c
}

// SaveRating provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveRating(ctx context.Context, customerID int64, topicID int, score int) error {
	ret := _mock.Called(ctx, customerID, topicID, score)

	if len(ret) == 0 {
		panic("no return value specified for SaveRating")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, int) error); ok {
		r0 = returnFunc(ctx, customerID, topicID, score)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SaveRating_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRating'
type MockRepository_SaveRating_Call struct {
	*mock.Call
}

// SaveRating is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID int64
//   - topicID int
//   - score int
func (_e *MockRepository_Expecter) SaveRating(ctx interface{}, customerID interface{}, topicID interface{}, score interface{}) *MockRepository_SaveRating_Call {
	return &MockRepository_SaveRating_Call{Call: _e.mock.On("SaveRating", ctx, customerID, topicID, score)}
}

func (_c *MockRepository_SaveRating_Call) Run(run func(ctx context.Context, customerID int64, topicID int, score int)) *MockRepository_SaveRating_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_SaveRating_Call) Return(err error) *MockRepository_SaveRating_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SaveRating_Call) RunAndReturn(run func(ctx context.Context, customerID int64, topicID int, score int) error) *MockRepository_SaveRating_Call {
	_c.Call.Return(run)
	return _c
}

// SaveTopic provides a mock function for the type MockRepository
func (_mock *MockRepository) SaveTopic(ctx context.Context, customerID int64, topicID int, categoryID int, langCode string) error {
	ret := _mock.Called(ctx, customerID, topicID, categoryID, langCode)

	if len(ret) == 0 {
		panic("no return value specified for SaveTopic")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, int, string) error); ok {
		r0 = returnFunc(ctx, customerID, topicID, categoryID, langCode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SaveTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveTopic'
type MockRepository_SaveTopic_Call struct {
	*mock.Call
}

// SaveTopic is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID int64
//   - topicID int
//   - categoryID int
//   - langCode string
func (_e *MockRepository_Expecter) SaveTopic(ctx interface{}, customerID interface{}, topicID interface{}, categoryID interface{}, langCode interface{}) *MockRepository_SaveTopic_Call {
	return &MockRepository_SaveTopic_Call{Call: _e.mock.On("SaveTopic", ctx, customerID, topicID, categoryID, langCode)}
}

func (_c *MockRepository_SaveTopic_Call) Run(run func(ctx context.Context, customerID int64, topicID int, categoryID int, langCode string)) *MockRepository_SaveTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepository_SaveTopic_Call) Return(err error) *MockRepository_SaveTopic_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SaveTopic_Call) RunAndReturn(run func(ctx context.Context, customerID int64, topicID int, categoryID int, langCode string) error) *MockRepository_SaveTopic_Call {
	_c.Call.Return(run)
	return _c
}

// SetTopicStatus provides a mock function for the type MockRepository
func (_mock *MockRepository) SetTopicStatus(ctx context.Context, topicID int, isClosed bool) error {
	ret := _mock.Called(ctx, topicID, isClosed)

	if len(ret) == 0 {
		panic("no return value specified for SetTopicStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, bool) error); ok {
		r0 = returnFunc(ctx, topicID, isClosed)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SetTopicStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTopicStatus'
type MockRepository_SetTopicStatus_Call struct {
	*mock.Call
}

// SetTopicStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - topicID int
//   - isClosed bool
func (_e *MockRepository_Expecter) SetTopicStatus(ctx interface{}, topicID interface{}, isClosed interface{}) *MockRepository_SetTopicStatus_Call {
	return &MockRepository_SetTopicStatus_Call{Call: _e.mock.On("SetTopicStatus", ctx, topicID, isClosed)}
}

func (_c *MockRepository_SetTopicStatus_Call) Run(run func(ctx context.Context, topicID int, isClosed bool)) *MockRepository_SetTopicStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_SetTopicStatus_Call) Return(err error) *MockRepository_SetTopicStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SetTopicStatus_Call) RunAndReturn(run func(ctx context.Context, topicID int, isClosed bool) error) *MockRepository_SetTopicStatus_Call {
	_c.Call.Return(run)
	return _c
}

// SetWaitingName provides a mock function for the type MockRepository
func (_mock *MockRepository) SetWaitingName(ctx context.Context, customerID int64) error {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for SetWaitingName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SetWaitingName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWaitingName'
type MockRepository_SetWaitingName_Call struct {
	*mock.Call
}

// SetWaitingName is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID int64
func (_e *MockRepository_Expecter) SetWaitingName(ctx interface{}, customerID interface{}) *MockRepository_SetWaitingName_Call {
	return &MockRepository_SetWaitingName_Call{Call: _e.mock.On("SetWaitingName", ctx, customerID)}
}

func (_c *MockRepository_SetWaitingName_Call) Run(run func(ctx context.Context, customerID int64)) *MockRepository_SetWaitingName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SetWaitingName_Call) Return(err error) *MockRepository_SetWaitingName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SetWaitingName_Call) RunAndReturn(run func(ctx context.Context, customerID int64) error) *MockRepository_SetWaitingName_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateActiveManager provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateActiveManager(ctx context.Context, topicID int, managerID int64) error {
	ret := _mock.Called(ctx, topicID, managerID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateActiveManager")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int64) error); ok {
		r0 = returnFunc(ctx, topicID, managerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateActiveManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateActiveManager'
type MockRepository_UpdateActiveManager_Call struct {
	*mock.Call
}

// UpdateActiveManager is a helper method to define mock.On call
//   - ctx context.Context
//   - topicID int
//   - managerID int64
func (_e *MockRepository_Expecter) UpdateActiveManager(ctx interface{}, topicID interface{}, managerID interface{}) *MockRepository_UpdateActiveManager_Call {
	return &MockRepository_UpdateActiveManager_Call{Call: _e.mock.On("UpdateActiveManager", ctx, topicID, managerID)}
}

func (_c *MockRepository_UpdateActiveManager_Call) Run(run func(ctx context.Context, topicID int, managerID int64)) *MockRepository_UpdateActiveManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateActiveManager_Call) Return(err error) *MockRepository_UpdateActiveManager_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateActiveManager_Call) RunAndReturn(run func(ctx context.Context, topicID int, managerID int64) error) *MockRepository_UpdateActiveManager_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBroadcastRecipientStatus provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateBroadcastRecipientStatus(ctx context.Context, recipientID int, status string, errText *string) error {
	ret := _mock.Called(ctx, recipientID, status, errText)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBroadcastRecipientStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, string, *string) error); ok {
		r0 = returnFunc(ctx, recipientID, status, errText)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateBroadcastRecipientStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBroadcastRecipientStatus'
type MockRepository_UpdateBroadcastRecipientStatus_Call struct {
	*mock.Call
}

// UpdateBroadcastRecipientStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - recipientID int
//   - status string
//   - errText *string
func (_e *MockRepository_Expecter) UpdateBroadcastRecipientStatus(ctx interface{}, recipientID interface{}, status interface{}, errText interface{}) *MockRepository_UpdateBroadcastRecipientStatus_Call {
	return &MockRepository_UpdateBroadcastRecipientStatus_Call{Call: _e.mock.On("UpdateBroadcastRecipientStatus", ctx, recipientID, status, errText)}
}

func (_c *MockRepository_UpdateBroadcastRecipientStatus_Call) Run(run func(ctx context.Context, recipientID int, status string, errText *string)) *MockRepository_UpdateBroadcastRecipientStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateBroadcastRecipientStatus_Call) Return(err error) *MockRepository_UpdateBroadcastRecipientStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateBroadcastRecipientStatus_Call) RunAndReturn(run func(ctx context.Context, recipientID int, status string, errText *string) error) *MockRepository_UpdateBroadcastRecipientStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCustomerLang provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateCustomerLang(ctx context.Context, customerID int64, langCode string) error {
	ret := _mock.Called(ctx, customerID, langCode)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCustomerLang")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, customerID, langCode)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateCustomerLang_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCustomerLang'
type MockRepository_UpdateCustomerLang_Call struct {
	*mock.Call
}

// UpdateCustomerLang is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID int64
//   - langCode string
func (_e *MockRepository_Expecter) UpdateCustomerLang(ctx interface{}, customerID interface{}, langCode interface{}) *MockRepository_UpdateCustomerLang_Call {
	return &MockRepository_UpdateCustomerLang_Call{Call: _e.mock.On("UpdateCustomerLang", ctx, customerID, langCode)}
}

func (_c *MockRepository_UpdateCustomerLang_Call) Run(run func(ctx context.Context, customerID int64, langCode string)) *MockRepository_UpdateCustomerLang_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateCustomerLang_Call) Return(err error) *MockRepository_UpdateCustomerLang_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateCustomerLang_Call) RunAndReturn(run func(ctx context.Context, customerID int64, langCode string) error) *MockRepository_UpdateCustomerLang_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateThrottle provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateThrottle(ctx context.Context, customerID int64) error {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateThrottle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateThrottle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateThrottle'
type MockRepository_UpdateThrottle_Call struct {
	*mock.Call
}

// UpdateThrottle is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID int64
func (_e *MockRepository_Expecter) UpdateThrottle(ctx interface{}, customerID interface{}) *MockRepository_UpdateThrottle_Call {
	return &MockRepository_UpdateThrottle_Call{Call: _e.mock.On("UpdateThrottle", ctx, customerID)}
}

func (_c *MockRepository_UpdateThrottle_Call) Run(run func(ctx context.Context, customerID int64)) *MockRepository_UpdateThrottle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateThrottle_Call) Return(err error) *MockRepository_UpdateThrottle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateThrottle_Call) RunAndReturn(run func(ctx context.Context, customerID int64) error) *MockRepository_UpdateThrottle_Call {
	_c.Call.Return(run)
	return _c
}
