// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLLM creates a new instance of MockLLM. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLLM(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLLM {
	mock := &MockLLM{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLLM is an autogenerated mock type for the LLM type
type MockLLM struct {
	mock.Mock
}

type MockLLM_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLLM) EXPECT() *MockLLM_Expecter {
	return &MockLLM_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockLLM
func (_mock *MockLLM) Close() {
	_mock.Called()
	return
}

// MockLLM_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockLLM_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockLLM_Expecter) Close() *MockLLM_Close_Call {
	return &MockLLM_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockLLM_Close_Call) Run(run func()) *MockLLM_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLLM_Close_Call) Return() *MockLLM_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLLM_Close_Call) RunAndReturn(run func()) *MockLLM_Close_Call {
	_c.Run(run)
	return _c
}

// Translate provides a mock function for the type MockLLM
func (_mock *MockLLM) Translate(ctx context.Context, text string, targetLang string) string {
	ret := _mock.Called(ctx, text, targetLang)

	if len(ret) == 0 {
		panic("no return value specified for Translate")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, text, targetLang)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockLLM_Translate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Translate'
type MockLLM_Translate_Call struct {
	*mock.Call
}

// Translate is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
//   - targetLang string
func (_e *MockLLM_Expecter) Translate(ctx interface{}, text interface{}, targetLang interface{}) *MockLLM_Translate_Call {
	return &MockLLM_Translate_Call{Call: _e.mock.On("Translate", ctx, text, targetLang)}
}

func (_c *MockLLM_Translate_Call) Run(run func(ctx context.Context, text string, targetLang string)) *MockLLM_Translate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLLM_Translate_Call) Return(s string) *MockLLM_Translate_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockLLM_Translate_Call) RunAndReturn(run func(ctx context.Context, text string, targetLang string) string) *MockLLM_Translate_Call {
	_c.Call.Return(run)
	return _c
}
