// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/mymmrac/telego"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBot creates a new instance of MockBot. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBot(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBot {
	mock := &MockBot{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBot is an autogenerated mock type for the Bot type
type MockBot struct {
	mock.Mock
}

type MockBot_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBot) EXPECT() *MockBot_Expecter {
	return &MockBot_Expecter{mock: &_m.Mock}
}

// AnswerCallbackQuery provides a mock function for the type MockBot
func (_mock *MockBot) AnswerCallbackQuery(ctx context.Context, params *telego.AnswerCallbackQueryParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for AnswerCallbackQuery")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *telego.AnswerCallbackQueryParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBot_AnswerCallbackQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnswerCallbackQuery'
type MockBot_AnswerCallbackQuery_Call struct {
	*mock.Call
}

// AnswerCallbackQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - params *telego.AnswerCallbackQueryParams
func (_e *MockBot_Expecter) AnswerCallbackQuery(ctx interface{}, params interface{}) *MockBot_AnswerCallbackQuery_Call {
	return &MockBot_AnswerCallbackQuery_Call{Call: _e.mock.On("AnswerCallbackQuery", ctx, params)}
}

func (_c *MockBot_AnswerCallbackQuery_Call) Run(run func(ctx context.Context, params *telego.AnswerCallbackQueryParams)) *MockBot_AnswerCallbackQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *telego.AnswerCallbackQueryParams
		if args[1] != nil {
			arg1 = args[1].(*telego.AnswerCallbackQueryParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBot_AnswerCallbackQuery_Call) Return(err error) *MockBot_AnswerCallbackQuery_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBot_AnswerCallbackQuery_Call) RunAndReturn(run func(ctx context.Context, params *telego.AnswerCallbackQueryParams) error) *MockBot_AnswerCallbackQuery_Call {
	_c.Call.Return(run)
	return _c
}

// CloseForumTopic provides a mock function for the type MockBot
func (_mock *MockBot) CloseForumTopic(ctx context.Context, params *telego.CloseForumTopicParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CloseForumTopic")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *telego.CloseForumTopicParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBot_CloseForumTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseForumTopic'
type MockBot_CloseForumTopic_Call struct {
	*mock.Call
}

// CloseForumTopic is a helper method to define mock.On call
//   - ctx context.Context
//   - params *telego.CloseForumTopicParams
func (_e *MockBot_Expecter) CloseForumTopic(ctx interface{}, params interface{}) *MockBot_CloseForumTopic_Call {
	return &MockBot_CloseForumTopic_Call{Call: _e.mock.On("CloseForumTopic", ctx, params)}
}

func (_c *MockBot_CloseForumTopic_Call) Run(run func(ctx context.Context, params *telego.CloseForumTopicParams)) *MockBot_CloseForumTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *telego.CloseForumTopicParams
		if args[1] != nil {
			arg1 = args[1].(*telego.CloseForumTopicParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBot_CloseForumTopic_Call) Return(err error) *MockBot_CloseForumTopic_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBot_CloseForumTopic_Call) RunAndReturn(run func(ctx context.Context, params *telego.CloseForumTopicParams) error) *MockBot_CloseForumTopic_Call {
	_c.Call.Return(run)
	return _c
}

// CopyMessage provides a mock function for the type MockBot
func (_mock *MockBot) CopyMessage(ctx context.Context, params *telego.CopyMessageParams) (*telego.MessageID, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CopyMessage")
	}

	var r0 *telego.MessageID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *telego.CopyMessageParams) (*telego.MessageID, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *telego.CopyMessageParams) *telego.MessageID); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telego.MessageID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *telego.CopyMessageParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBot_CopyMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyMessage'
type MockBot_CopyMessage_Call struct {
	*mock.Call
}

// CopyMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - params *telego.CopyMessageParams
func (_e *MockBot_Expecter) CopyMessage(ctx interface{}, params interface{}) *MockBot_CopyMessage_Call {
	return &MockBot_CopyMessage_Call{Call: _e.mock.On("CopyMessage", ctx, params)}
}

func (_c *MockBot_CopyMessage_Call) Run(run func(ctx context.Context, params *telego.CopyMessageParams)) *MockBot_CopyMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *telego.CopyMessageParams
		if args[1] != nil {
			arg1 = args[1].(*telego.CopyMessageParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBot_CopyMessage_Call) Return(messageID *telego.MessageID, err error) *MockBot_CopyMessage_Call {
	_c.Call.Return(messageID, err)
	return _c
}

func (_c *MockBot_CopyMessage_Call) RunAndReturn(run func(ctx context.Context, params *telego.CopyMessageParams) (*telego.MessageID, error)) *MockBot_CopyMessage_Call {
	_c.Call.Return(run)
	return _c
}

// CreateForumTopic provides a mock function for the type MockBot
func (_mock *MockBot) CreateForumTopic(ctx context.Context, params *telego.CreateForumTopicParams) (*telego.ForumTopic, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateForumTopic")
	}

	var r0 *telego.ForumTopic
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *telego.CreateForumTopicParams) (*telego.ForumTopic, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *telego.CreateForumTopicParams) *telego.ForumTopic); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telego.ForumTopic)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *telego.CreateForumTopicParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBot_CreateForumTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateForumTopic'
type MockBot_CreateForumTopic_Call struct {
	*mock.Call
}

// CreateForumTopic is a helper method to define mock.On call
//   - ctx context.Context
//   - params *telego.CreateForumTopicParams
func (_e *MockBot_Expecter) CreateForumTopic(ctx interface{}, params interface{}) *MockBot_CreateForumTopic_Call {
	return &MockBot_CreateForumTopic_Call{Call: _e.mock.On("CreateForumTopic", ctx, params)}
}

func (_c *MockBot_CreateForumTopic_Call) Run(run func(ctx context.Context, params *telego.CreateForumTopicParams)) *MockBot_CreateForumTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *telego.CreateForumTopicParams
		if args[1] != nil {
			arg1 = args[1].(*telego.CreateForumTopicParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBot_CreateForumTopic_Call) Return(forumTopic *telego.ForumTopic, err error) *MockBot_CreateForumTopic_Call {
	_c.Call.Return(forumTopic, err)
	return _c
}

func (_c *MockBot_CreateForumTopic_Call) RunAndReturn(run func(ctx context.Context, params *telego.CreateForumTopicParams) (*telego.ForumTopic, error)) *MockBot_CreateForumTopic_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMessage provides a mock function for the type MockBot
func (_mock *MockBot) DeleteMessage(ctx context.Context, params *telego.DeleteMessageParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *telego.DeleteMessageParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBot_DeleteMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessage'
type MockBot_DeleteMessage_Call struct {
	*mock.Call
}

// DeleteMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - params *telego.DeleteMessageParams
func (_e *MockBot_Expecter) DeleteMessage(ctx interface{}, params interface{}) *MockBot_DeleteMessage_Call {
	return &MockBot_DeleteMessage_Call{Call: _e.mock.On("DeleteMessage", ctx, params)}
}

func (_c *MockBot_DeleteMessage_Call) Run(run func(ctx context.Context, params *telego.DeleteMessageParams)) *MockBot_DeleteMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *telego.DeleteMessageParams
		if args[1] != nil {
			arg1 = args[1].(*telego.DeleteMessageParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBot_DeleteMessage_Call) Return(err error) *MockBot_DeleteMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBot_DeleteMessage_Call) RunAndReturn(run func(ctx context.Context, params *telego.DeleteMessageParams) error) *MockBot_DeleteMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetChatAdministrators provides a mock function for the type MockBot
func (_mock *MockBot) GetChatAdministrators(ctx context.Context, params *telego.GetChatAdministratorsParams) ([]telego.ChatMember, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetChatAdministrators")
	}

	var r0 []telego.ChatMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *telego.GetChatAdministratorsParams) ([]telego.ChatMember, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *telego.GetChatAdministratorsParams) []telego.ChatMember); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]telego.ChatMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *telego.GetChatAdministratorsParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBot_GetChatAdministrators_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatAdministrators'
type MockBot_GetChatAdministrators_Call struct {
	*mock.Call
}

// GetChatAdministrators is a helper method to define mock.On call
//   - ctx context.Context
//   - params *telego.GetChatAdministratorsParams
func (_e *MockBot_Expecter) GetChatAdministrators(ctx interface{}, params interface{}) *MockBot_GetChatAdministrators_Call {
	return &MockBot_GetChatAdministrators_Call{Call: _e.mock.On("GetChatAdministrators", ctx, params)}
}

func (_c *MockBot_GetChatAdministrators_Call) Run(run func(ctx context.Context, params *telego.GetChatAdministratorsParams)) *MockBot_GetChatAdministrators_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *telego.GetChatAdministratorsParams
		if args[1] != nil {
			arg1 = args[1].(*telego.GetChatAdministratorsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBot_GetChatAdministrators_Call) Return(chatMembers []telego.ChatMember, err error) *MockBot_GetChatAdministrators_Call {
	_c.Call.Return(chatMembers, err)
	return _c
}

func (_c *MockBot_GetChatAdministrators_Call) RunAndReturn(run func(ctx context.Context, params *telego.GetChatAdministratorsParams) ([]telego.ChatMember, error)) *MockBot_GetChatAdministrators_Call {
	_c.Call.Return(run)
	return _c
}

// GetChatMember provides a mock function for the type MockBot
func (_mock *MockBot) GetChatMember(ctx context.Context, params *telego.GetChatMemberParams) (telego.ChatMember, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetChatMember")
	}

	var r0 telego.ChatMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *telego.GetChatMemberParams) (telego.ChatMember, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *telego.GetChatMemberParams) telego.ChatMember); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(telego.ChatMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *telego.GetChatMemberParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBot_GetChatMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatMember'
type MockBot_GetChatMember_Call struct {
	*mock.Call
}

// GetChatMember is a helper method to define mock.On call
//   - ctx context.Context
//   - params *telego.GetChatMemberParams
func (_e *MockBot_Expecter) GetChatMember(ctx interface{}, params interface{}) *MockBot_GetChatMember_Call {
	return &MockBot_GetChatMember_Call{Call: _e.mock.On("GetChatMember", ctx, params)}
}

func (_c *MockBot_GetChatMember_Call) Run(run func(ctx context.Context, params *telego.GetChatMemberParams)) *MockBot_GetChatMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *telego.GetChatMemberParams
		if args[1] != nil {
			arg1 = args[1].(*telego.GetChatMemberParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBot_GetChatMember_Call) Return(chatMember telego.ChatMember, err error) *MockBot_GetChatMember_Call {
	_c.Call.Return(chatMember, err)
	return _c
}

func (_c *MockBot_GetChatMember_Call) RunAndReturn(run func(ctx context.Context, params *telego.GetChatMemberParams) (telego.ChatMember, error)) *MockBot_GetChatMember_Call {
	_c.Call.Return(run)
	return _c
}

// GetFile provides a mock function for the type MockBot
func (_mock *MockBot) GetFile(ctx context.Context, params *telego.GetFileParams) (*telego.File, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetFile")
	}

	var r0 *telego.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *telego.GetFileParams) (*telego.File, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *telego.GetFileParams) *telego.File); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telego.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *telego.GetFileParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBot_GetFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFile'
type MockBot_GetFile_Call struct {
	*mock.Call
}

// GetFile is a helper method to define mock.On call
//   - ctx context.Context
//   - params *telego.GetFileParams
func (_e *MockBot_Expecter) GetFile(ctx interface{}, params interface{}) *MockBot_GetFile_Call {
	return &MockBot_GetFile_Call{Call: _e.mock.On("GetFile", ctx, params)}
}

func (_c *MockBot_GetFile_Call) Run(run func(ctx context.Context, params *telego.GetFileParams)) *MockBot_GetFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *telego.GetFileParams
		if args[1] != nil {
			arg1 = args[1].(*telego.GetFileParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBot_GetFile_Call) Return(file *telego.File, err error) *MockBot_GetFile_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockBot_GetFile_Call) RunAndReturn(run func(ctx context.Context, params *telego.GetFileParams) (*telego.File, error)) *MockBot_GetFile_Call {
	_c.Call.Return(run)
	return _c
}

// ReopenForumTopic provides a mock function for the type MockBot
func (_mock *MockBot) ReopenForumTopic(ctx context.Context, params *telego.ReopenForumTopicParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ReopenForumTopic")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *telego.ReopenForumTopicParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBot_ReopenForumTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReopenForumTopic'
type MockBot_ReopenForumTopic_Call struct {
	*mock.Call
}

// ReopenForumTopic is a helper method to define mock.On call
//   - ctx context.Context
//   - params *telego.ReopenForumTopicParams
func (_e *MockBot_Expecter) ReopenForumTopic(ctx interface{}, params interface{}) *MockBot_ReopenForumTopic_Call {
	return &MockBot_ReopenForumTopic_Call{Call: _e.mock.On("ReopenForumTopic", ctx, params)}
}

func (_c *MockBot_ReopenForumTopic_Call) Run(run func(ctx context.Context, params *telego.ReopenForumTopicParams)) *MockBot_ReopenForumTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *telego.ReopenForumTopicParams
		if args[1] != nil {
			arg1 = args[1].(*telego.ReopenForumTopicParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBot_ReopenForumTopic_Call) Return(err error) *MockBot_ReopenForumTopic_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBot_ReopenForumTopic_Call) RunAndReturn(run func(ctx context.Context, params *telego.ReopenForumTopicParams) error) *MockBot_ReopenForumTopic_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function for the type MockBot
func (_mock *MockBot) SendMessage(ctx context.Context, params *telego.SendMessageParams) (*telego.Message, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 *telego.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *telego.SendMessageParams) (*telego.Message, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *telego.SendMessageParams) *telego.Message); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telego.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *telego.SendMessageParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBot_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockBot_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - params *telego.SendMessageParams
func (_e *MockBot_Expecter) SendMessage(ctx interface{}, params interface{}) *MockBot_SendMessage_Call {
	return &MockBot_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, params)}
}

func (_c *MockBot_SendMessage_Call) Run(run func(ctx context.Context, params *telego.SendMessageParams)) *MockBot_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *telego.SendMessageParams
		if args[1] != nil {
			arg1 = args[1].(*telego.SendMessageParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBot_SendMessage_Call) Return(message *telego.Message, err error) *MockBot_SendMessage_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockBot_SendMessage_Call) RunAndReturn(run func(ctx context.Context, params *telego.SendMessageParams) (*telego.Message, error)) *MockBot_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SendPhoto provides a mock function for the type MockBot
func (_mock *MockBot) SendPhoto(ctx context.Context, params *telego.SendPhotoParams) (*telego.Message, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SendPhoto")
	}

	var r0 *telego.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *telego.SendPhotoParams) (*telego.Message, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *telego.SendPhotoParams) *telego.Message); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telego.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *telego.SendPhotoParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBot_SendPhoto_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPhoto'
type MockBot_SendPhoto_Call struct {
	*mock.Call
}

// SendPhoto is a helper method to define mock.On call
//   - ctx context.Context
//   - params *telego.SendPhotoParams
func (_e *MockBot_Expecter) SendPhoto(ctx interface{}, params interface{}) *MockBot_SendPhoto_Call {
	return &MockBot_SendPhoto_Call{Call: _e.mock.On("SendPhoto", ctx, params)}
}

func (_c *MockBot_SendPhoto_Call) Run(run func(ctx context.Context, params *telego.SendPhotoParams)) *MockBot_SendPhoto_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *telego.SendPhotoParams
		if args[1] != nil {
			arg1 = args[1].(*telego.SendPhotoParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBot_SendPhoto_Call) Return(message *telego.Message, err error) *MockBot_SendPhoto_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockBot_SendPhoto_Call) RunAndReturn(run func(ctx context.Context, params *telego.SendPhotoParams) (*telego.Message, error)) *MockBot_SendPhoto_Call {
	_c.Call.Return(run)
	return _c
}

// Token provides a mock function for the type MockBot
func (_mock *MockBot) Token() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Token")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockBot_Token_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Token'
type MockBot_Token_Call struct {
	*mock.Call
}

// Token is a helper method to define mock.On call
func (_e *MockBot_Expecter) Token() *MockBot_Token_Call {
	return &MockBot_Token_Call{Call: _e.mock.On("Token")}
}

func (_c *MockBot_Token_Call) Run(run func()) *MockBot_Token_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBot_Token_Call) Return(s string) *MockBot_Token_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockBot_Token_Call) RunAndReturn(run func() string) *MockBot_Token_Call {
	_c.Call.Return(run)
	return _c
}
