// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-support-bot/internal/app/clients/telegram"

	"github.com/mymmrac/telego"
	"github.com/mymmrac/telego/telegohandler"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTelegram creates a new instance of MockTelegram. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTelegram(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTelegram {
	mock := &MockTelegram{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTelegram is an autogenerated mock type for the Telegram type
type MockTelegram struct {
	mock.Mock
}

type MockTelegram_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTelegram) EXPECT() *MockTelegram_Expecter {
	return &MockTelegram_Expecter{mock: &_m.Mock}
}

// ClearCache provides a mock function for the type MockTelegram
func (_mock *MockTelegram) ClearCache() {
	_mock.Called()
	return
}

// MockTelegram_ClearCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearCache'
type MockTelegram_ClearCache_Call struct {
	*mock.Call
}

// ClearCache is a helper method to define mock.On call
func (_e *MockTelegram_Expecter) ClearCache() *MockTelegram_ClearCache_Call {
	return &MockTelegram_ClearCache_Call{Call: _e.mock.On("ClearCache")}
}

func (_c *MockTelegram_ClearCache_Call) Run(run func()) *MockTelegram_ClearCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTelegram_ClearCache_Call) Return() *MockTelegram_ClearCache_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTelegram_ClearCache_Call) RunAndReturn(run func()) *MockTelegram_ClearCache_Call {
	_c.Run(run)
	return _c
}

// GetBot provides a mock function for the type MockTelegram
func (_mock *MockTelegram) GetBot() telegram.Bot {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBot")
	}

	var r0 telegram.Bot
	if returnFunc, ok := ret.Get(0).(func() telegram.Bot); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(telegram.Bot)
		}
	}
	return r0
}

// MockTelegram_GetBot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBot'
type MockTelegram_GetBot_Call struct {
	*mock.Call
}

// GetBot is a helper method to define mock.On call
func (_e *MockTelegram_Expecter) GetBot() *MockTelegram_GetBot_Call {
	return &MockTelegram_GetBot_Call{Call: _e.mock.On("GetBot")}
}

func (_c *MockTelegram_GetBot_Call) Run(run func()) *MockTelegram_GetBot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTelegram_GetBot_Call) Return(bot telegram.Bot) *MockTelegram_GetBot_Call {
	_c.Call.Return(bot)
	return _c
}

func (_c *MockTelegram_GetBot_Call) RunAndReturn(run func() telegram.Bot) *MockTelegram_GetBot_Call {
	_c.Call.Return(run)
	return _c
}

// GetChatAdministrators provides a mock function for the type MockTelegram
func (_mock *MockTelegram) GetChatAdministrators(ctx context.Context, chatID int64) ([]telego.ChatMember, error) {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for GetChatAdministrators")
	}

	var r0 []telego.ChatMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]telego.ChatMember, error)); ok {
		return returnFunc(ctx, chatID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []telego.ChatMember); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]telego.ChatMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTelegram_GetChatAdministrators_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatAdministrators'
type MockTelegram_GetChatAdministrators_Call struct {
	*mock.Call
}

// GetChatAdministrators is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *MockTelegram_Expecter) GetChatAdministrators(ctx interface{}, chatID interface{}) *MockTelegram_GetChatAdministrators_Call {
	return &MockTelegram_GetChatAdministrators_Call{Call: _e.mock.On("GetChatAdministrators", ctx, chatID)}
}

func (_c *MockTelegram_GetChatAdministrators_Call) Run(run func(ctx context.Context, chatID int64)) *MockTelegram_GetChatAdministrators_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTelegram_GetChatAdministrators_Call) Return(chatMembers []telego.ChatMember, err error) *MockTelegram_GetChatAdministrators_Call {
	_c.Call.Return(chatMembers, err)
	return _c
}

func (_c *MockTelegram_GetChatAdministrators_Call) RunAndReturn(run func(ctx context.Context, chatID int64) ([]telego.ChatMember, error)) *MockTelegram_GetChatAdministrators_Call {
	_c.Call.Return(run)
	return _c
}

// IsCustomer provides a mock function for the type MockTelegram
func (_mock *MockTelegram) IsCustomer(supportGroup int64) telegohandler.Predicate {
	ret := _mock.Called(supportGroup)

	if len(ret) == 0 {
		panic("no return value specified for IsCustomer")
	}

	var r0 telegohandler.Predicate
	if returnFunc, ok := ret.Get(0).(func(int64) telegohandler.Predicate); ok {
		r0 = returnFunc(supportGroup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(telegohandler.Predicate)
		}
	}
	return r0
}

// MockTelegram_IsCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsCustomer'
type MockTelegram_IsCustomer_Call struct {
	*mock.Call
}

// IsCustomer is a helper method to define mock.On call
//   - supportGroup int64
func (_e *MockTelegram_Expecter) IsCustomer(supportGroup interface{}) *MockTelegram_IsCustomer_Call {
	return &MockTelegram_IsCustomer_Call{Call: _e.mock.On("IsCustomer", supportGroup)}
}

func (_c *MockTelegram_IsCustomer_Call) Run(run func(supportGroup int64)) *MockTelegram_IsCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTelegram_IsCustomer_Call) Return(predicate telegohandler.Predicate) *MockTelegram_IsCustomer_Call {
	_c.Call.Return(predicate)
	return _c
}

func (_c *MockTelegram_IsCustomer_Call) RunAndReturn(run func(supportGroup int64) telegohandler.Predicate) *MockTelegram_IsCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// IsManager provides a mock function for the type MockTelegram
func (_mock *MockTelegram) IsManager(ctx context.Context, supportGroup int64, userID int64) bool {
	ret := _mock.Called(ctx, supportGroup, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsManager")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) bool); ok {
		r0 = returnFunc(ctx, supportGroup, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTelegram_IsManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsManager'
type MockTelegram_IsManager_Call struct {
	*mock.Call
}

// IsManager is a helper method to define mock.On call
//   - ctx context.Context
//   - supportGroup int64
//   - userID int64
func (_e *MockTelegram_Expecter) IsManager(ctx interface{}, supportGroup interface{}, userID interface{}) *MockTelegram_IsManager_Call {
	return &MockTelegram_IsManager_Call{Call: _e.mock.On("IsManager", ctx, supportGroup, userID)}
}

func (_c *MockTelegram_IsManager_Call) Run(run func(ctx context.Context, supportGroup int64, userID int64)) *MockTelegram_IsManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTelegram_IsManager_Call) Return(b bool) *MockTelegram_IsManager_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTelegram_IsManager_Call) RunAndReturn(run func(ctx context.Context, supportGroup int64, userID int64) bool) *MockTelegram_IsManager_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleTestMode provides a mock function for the type MockTelegram
func (_mock *MockTelegram) ToggleTestMode(userID int64) bool {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for ToggleTestMode")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(int64) bool); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTelegram_ToggleTestMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleTestMode'
type MockTelegram_ToggleTestMode_Call struct {
	*mock.Call
}

// ToggleTestMode is a helper method to define mock.On call
//   - userID int64
func (_e *MockTelegram_Expecter) ToggleTestMode(userID interface{}) *MockTelegram_ToggleTestMode_Call {
	return &MockTelegram_ToggleTestMode_Call{Call: _e.mock.On("ToggleTestMode", userID)}
}

func (_c *MockTelegram_ToggleTestMode_Call) Run(run func(userID int64)) *MockTelegram_ToggleTestMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTelegram_ToggleTestMode_Call) Return(b bool) *MockTelegram_ToggleTestMode_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTelegram_ToggleTestMode_Call) RunAndReturn(run func(userID int64) bool) *MockTelegram_ToggleTestMode_Call {
	_c.Call.Return(run)
	return _c
}
